authentication/urls.py
from django.urls import path
from authentication.views import *
app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/',logout,name='logout'),
    path('',redir_homepage, name="redir_homepage"),
    path('register/',register_pengguna, name="register_pengguna"),

]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('daftar_kontributor/', daftar_kontributor, name='daftar_kontributor'),
    path('langganan/', langganan, name='langganan'),
    path('halaman_beli/<str:paket>', halaman_beli, name='halaman_beli'),
    path('register/', show_register, name='show_register'),
    path('', show_home, name="show_home"),
    path('unduhan/', daftar_unduhan, name='daftar_unduhan'),
    path('delete-unduhan/', delete_unduhan, name='delete_unduhan'),
    path('tambah-unduhan/', tambah_unduhan, name='tambah_unduhan'),
    path('favorit/', daftar_favorit, name='daftar_favorit'),
    path('isi-daftar-favorit/<str:judul>/', isi_daftar_favorit, name='isi_daftar_favorit'),
    path('delete-daftar-favorit/', delete_daftar_favorit, name='delete_daftar_favorit'),
    path('delete-dari-favorit/', delete_dari_favorit, name='delete_dari_favorit'),
    path('add-to-favorit/', add_to_favorit, name='add_to_favorit'),
    path('show_daftar_tayangan/', show_daftar_tayangan, name="show_daftar_tayangan"),
    path('tayangan/<str:id_tayangan>', show_tayangan, name="show_tayangan"),
    path('show_episode/<str:id_tayangan>/<str:judul>/<str:sub_judul>/', show_episode, name="show_episode"),
    path('insert_ulasan/', insert_ulasan, name="insert_ulasan"),
    path('compute_riwayat_nonton/', compute_riwayat_nonton, name="compute_riwayat_nonton"),
    path('search_tayangan/', search_tayangan, name='search_tayangan'),
]

tugas_kelompok_basdat_c14/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/',include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    </head>

    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/navbar.html
<!-- Navigation (nanti tambah if else dalam kalau udh authenticated) -->
<nav class="navbar navbar-light bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1" style="color: aliceblue;">PacilFlix - C14</span>
    {% if request.session.logged_in %}
    <p class="navbar-brand mb-0 h1" style="color: rgb(135, 222, 136);">=={{ request.session.username }}==</p>
    <div>
    
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:show_home' %}">Home</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:show_daftar_tayangan' %}">Daftar Tayangan</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:daftar_kontributor' %}">Kontributor</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:daftar_favorit' %}">Favorit</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:daftar_unduhan' %}">Unduhan</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:langganan' %}">Langganan</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'authentication:logout' %}">Logout</a>

    {% else %}
    <div>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:show_home' %}">Home</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'main:show_daftar_tayangan' %}">Daftar Trailer</a>
    <a class="navbar-brand" style="color: aliceblue;" href="{% url 'authentication:login' %}">Login</a>

  {% endif %}

  
  </div>
</div>
</nav>