authentication/urls.py
from django.urls import path
from authentication.views import *
app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/',logout,name='logout'),
    path('',redir_homepage, name="redir_homepage"),
    path('register/',register_pengguna, name="register_pengguna"),

]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('daftar_kontributor/', daftar_kontributor, name='daftar_kontributor'),
    path('langganan/', langganan, name='langganan'),
    path('halaman_beli/<str:paket>', halaman_beli, name='halaman_beli'),
    path('register/', show_register, name='show_register'),
    path('', show_home, name="show_home"),
    path('unduhan/', daftar_unduhan, name='daftar_unduhan'),
    path('delete-unduhan/', delete_unduhan, name='delete_unduhan'),
    path('tambah-unduhan/', tambah_unduhan, name='tambah_unduhan'),
    path('favorit/', daftar_favorit, name='daftar_favorit'),
    path('isi-daftar-favorit/<str:judul>/', isi_daftar_favorit, name='isi_daftar_favorit'),
    path('delete-daftar-favorit/', delete_daftar_favorit, name='delete_daftar_favorit'),
    path('delete-dari-favorit/', delete_dari_favorit, name='delete_dari_favorit'),
    path('add-to-favorit/', add_to_favorit, name='add_to_favorit'),
    path('show_daftar_tayangan/', show_daftar_tayangan, name="show_daftar_tayangan"),
    path('tayangan/<str:id_tayangan>', show_tayangan, name="show_tayangan"),
    path('show_episode/<str:id_tayangan>/<str:judul>/<str:sub_judul>/', show_episode, name="show_episode"),
    path('insert_ulasan/', insert_ulasan, name="insert_ulasan"),
    path('compute_riwayat_nonton/', compute_riwayat_nonton, name="compute_riwayat_nonton"),
    path('search_tayangan/', search_tayangan, name='search_tayangan'),
]

tugas_kelompok_basdat_c14/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/',include('authentication.urls')),
]

main/views.py
from datetime import datetime, timedelta, date
import math
from django.utils import timezone
from django.http import Http404
from django.shortcuts import redirect, render
from django.db import InternalError, connection as conn
from django.views.decorators.csrf import csrf_exempt
from functools import wraps
import json
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseNotFound, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.urls import reverse
from dateutil import parser
from django.contrib import messages
from urllib.parse import unquote
from django.views.decorators.http import require_http_methods
import psycopg2


# Create your views here.

def login_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        if "username" in request.session:
            # User is logged in, proceed to the view
            return view_func(request, *args, **kwargs)
        else:
            # User is a guest, redirect to login page
            return redirect('authentication:login')
    return _wrapped_view

def check_package(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        if check_active_package(request):
            return view_func(request, *args, **kwargs)
        else:
            return redirect('main:langganan')
    return _wrapped_view

def check_active_package(request):
    displayTombol = False
    if "username" in request.session:
        with conn.cursor() as cursor:
            cursor.execute("SET search_path TO extensions")
            now = datetime.now()

            query = """
                SELECT * FROM TRANSACTION
                WHERE username = %s AND start_date_time <= %s AND end_date_time >= %s
            """

            cursor.execute(query, (request.session["username"], now, now))

            result = cursor.fetchone()

            if result is not None:
                displayTombol = True

    return displayTombol

def daftar_kontributor(request):
    context = {
        "kontributor_list": [],
        "error": None}
    try:
        cursor = conn.cursor()
        query = """
        SELECT 
            nama, 
            string_agg(tipe, ', ') AS tipe, 
            jenis_kelamin, 
            kewarganegaraan
        FROM (
            SELECT 
                c.nama, 
                'Penulis Skenario' AS tipe, 
                c.jenis_kelamin, 
                c.kewarganegaraan
            FROM 
                contributors c
            JOIN 
                penulis_skenario ps ON c.id = ps.id
            UNION
            SELECT 
                c.nama, 
                'Pemain' AS tipe, 
                c.jenis_kelamin, 
                c.kewarganegaraan
            FROM 
                contributors c
            JOIN 
                pemain p ON c.id = p.id
            UNION
            SELECT 
                c.nama, 
                'Sutradara' AS tipe, 
                c.jenis_kelamin, 
                c.kewarganegaraan
            FROM 
                contributors c
            JOIN 
                sutradara s ON c.id = s.id
        ) AS combined
        GROUP BY 
            nama, 
            jenis_kelamin, 
            kewarganegaraan;
        """

        cursor.execute(query)
        kontributor_output = cursor.fetchall()

        context = {
        'kontributor_list' : [{
            "nama": res[0],
            "tipe": res[1],
            "jenis_kelamin": f'{"Laki-laki" if res[2] == 0 else "Perempuan"}',
            "kewarganegaraan": res[3]
        }
        for res in kontributor_output],
        }

    except (Exception, psycopg2.Error) as error:
        print("Error while fetching data from PostgreSQL", error)
        context["error"] = "Error while fetching data from PostgreSQL"

    finally:
        # closing database connection.
        if 'cursor' in locals():
            cursor.close()
        if 'conn' in locals() and conn:
            conn.close()
            print("PostgreSQL connection is closed")

    return render(request, "daftar_kontributor.html", context)


@require_http_methods(["GET","POST"])
def langganan(request):
    context = {}
    try:
        cursor = conn.cursor()
        # print(request.session.get('username'))
        #todo
        query = f"""SELECT distinct
            paket.nama, 
            paket.harga, 
            paket.resolusi_layar, 
            dukungan_perangkat.dukungan_perangkat AS dukungan_perangkat, 
            transaction.start_date_time, 
            transaction.end_date_time
        FROM 
            paket
        JOIN 
            dukungan_perangkat 
        ON 
            paket.nama = dukungan_perangkat.nama_paket
        JOIN 
            transaction 
        ON 
            paket.nama = transaction.nama_paket
        JOIN 
            pengguna 
        ON 
            transaction.username = '{request.session.get('username')}'
        WHERE
            transaction.end_date_time > NOW();"""

        cursor.execute(query)
        paket_langganan_output = cursor.fetchall()

        #todo
        query = """
            SELECT paket.nama, harga, resolusi_layar, string_agg(dukungan_perangkat, ', ')
            FROM paket        
            JOIN dukungan_perangkat ON paket.nama = dukungan_perangkat.nama_paket
            GROUP BY paket.nama, harga, resolusi_layar;
        """

        cursor.execute(query)
        paket_lain_output = cursor.fetchall()

        list_paket_lain = []

        for res in paket_lain_output:
            list_paket_lain.append({  
                "nama" : res[0],
                "harga" : res[1],
                "resolusi_layar": res[2],
                "dukungan_perangkat": res[3]
            })
        
        #todo
        query = f"""
        select 
        nama, transaction.start_date_time, transaction.end_date_time, metode_pembayaran, timestamp_pembayaran, harga
        from paket 
        join transaction on paket.nama = transaction.nama_paket
        join pengguna on pengguna.username = '{request.session.get('username')}'
        group by nama, transaction.start_date_time, transaction.end_date_time, metode_pembayaran, timestamp_pembayaran;
        """

        cursor.execute(query)
        riwayat_transaksi_output = cursor.fetchall()

        # list_riwayat_transaksi = []

        # for res in riwayat_transaksi_output:
        #     list_riwayat_transaksi.append({     
        #         "nama_paket": res[0],
        #         "tanggal_dimulai": res[1],
        #         "tanggal_akhir": res[2],
        #         "metode_pembayaran": res[3],
        #         "tanggal_pembayaran": res[4],
        #         "total_pembayaran" : res[5]
        #     })

        # cursor.execute(query)

        context = {
        'list_paket_langganan_aktif' : [{
            "nama" : res[0],
            "harga" : res[1],
            "resolusi_layar" : res[2],
            "dukungan_perangkat" : res[3],
            "tanggal_dimulai" : res[4],
            "tanggal_akhir" : res[5]
        }
        for res in paket_langganan_output],
        'list_paket_lain' : [{
            "nama" : res[0],
            "harga" : res[1],
            "resolusi_layar": res[2],
            "dukungan_perangkat": res[3]
        }
        for res in paket_lain_output],
        'list_riwayat_transaksi' : [{
            "nama_paket": res[0],
            "tanggal_dimulai": res[1],
            "tanggal_akhir": res[2],
            "metode_pembayaran": res[3],
            "tanggal_pembayaran": res[4],
            "total_pembayaran" : res[5]
        }
        for res in riwayat_transaksi_output],
        }
        
        # print(context)
        # return render(request, "langganan.html", context)

    except (Exception, psycopg2.Error) as error:
        print("Error while fetching data from PostgreSQL", error)

    finally:
        # closing database connection.
        if conn:
            cursor.close()
            conn.close()
            print("PostgreSQL connection is closed")

    return render(request, "langganan.html", context)
            

@require_http_methods(["GET","POST"])
def halaman_beli(request, paket):
    list_metode_pembayaran=['Transfer Bank','Kartu Kredit','E-Wallet']
    if request.session.get('username') is not None:
        try:          
            cursor = conn.cursor()
            if request.method == "POST":
                paket_lain_list=[]
                print(request.POST)
                print(request.POST.get("BuyStatus"))
                if(request.POST.get("BuyStatus") is not None):
                
                    package_name = paket
                    username = request.session.get('username')
                    payment_method = request.POST['payment_method']
                    cursor.execute(
                        f"""select * from transaction where username = {request.session.get('username')}
                        and end_date_time > CURRENT_TIMESTAMP
                        """
                    )
                    langganan_aktif = cursor.fetchall() 
                    if len(langganan_aktif) == 0:
                        # Insert new transaction
                        cursor.execute(
                            """
                            INSERT INTO transaction (username, nama_paket, start_date_time, end_date_time, metode_pembayaran, timestamp_pembayaran) 
                            VALUES (%s, %s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + interval '30 days', %s, CURRENT_TIMESTAMP)
                            """,
                            (username, package_name, payment_method)
                        )
                    else:
                        # Update existing transaction
                        cursor.execute(
                            """
                            UPDATE transaction
                            SET end_date_time = CURRENT_TIMESTAMP + interval '30 days',
                                metode_pembayaran = %s,

main/templates/daftar_favorit.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 mt-4">
      <div class="card">
        <div class="card-header text-center">Daftar Favorit</div>

        <div class="card-body">
          <table class="table table-striped text-center">
            <thead>
              <tr>
                <th>Judul</th>
                <th>Waktu Dibuat</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              {% for favorit in daftar_favorit %}
              <tr>
                <td><a href="{% url 'main:isi_daftar_favorit' judul=favorit.0|urlencode %}">{{ favorit.0 }}</a></td>
                <td>{{ favorit.1 }}</td>
                <td>
                  <button
                    class="btn btn-danger delete-btn"
                    data-judul="{{ favorit.0 }}"
                  >
                    Hapus
                  </button>
                </td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="3">Daftar favorit masih kosong...</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
      document.querySelectorAll(".delete-btn").forEach((button) => {
        button.addEventListener("click", function () {
          const judul = this.getAttribute("data-judul");
  
          fetch(`{% url 'main:delete_daftar_favorit' %}`, {
            method: "DELETE",
            headers: {
              "Content-Type": "application/json",
              "X-CSRFToken": "{{ csrf_token }}",
            },
            body: JSON.stringify({ judul }),
          })
            .then((response) => {
              if (response.ok) {
                return response.text();
              } else {
                throw new Error("Something went wrong on the server.");
              }
            })
            .then((data) => {
              console.log(data);
              location.reload();
            })
            .catch((error) => console.error("Error:", error));
        });
      });
    });
  </script>

{% endblock content %}

main/templates/halaman_film.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Halaman Film</title>
{% endblock meta %}

{% block content %}

<body>
    <h1>HALAMAN FILM</h1>
    <h2>Judul: {{ judul }}</h2>

    <!-- TODO IMPLEMENT -->
    {% now "Y-m-d" as today %}
    {% if today >= release_date_film %}
        <label for="progress">Progress:</label>
        <button id="toggleButton">Tonton</button>
        <input type="range" min="0" max="100" value="0" id="movieSlider">
        <p id="sliderPosition">0 %</p>
        <script>
            var slider = document.getElementById("movieSlider");
            var output = document.getElementById("sliderPosition");
            slider.oninput = function() {
                output.innerHTML = this.value + " %";
            }
        </script>
    {% endif %}
    
    <form method="POST" action="{% url 'main:tambah_unduhan' %}">
        {% csrf_token %}
        <input type="hidden" name="id_tayangan_unduhan" value="{{ id }}">
        <input type="hidden" name="judul" value="{{ judul }}">
        <button type="submit" >Unduh Tayangan</button>
    </form>

    <button data-bs-toggle="modal" data-bs-target="#favoritModal">Favorit Tayangan</button>

    <p>Total View: {{ total_view }}</p>
    <p>Rating Rata-Rata: {{ avg_rating }}</p>
    <p>Sinopsis: {{ sinopsis }}</p>
    <p>Durasi Film: {{ durasi_film }} menit</p>
    <p>Tanggal Rilis Film: {{ release_date_film }}</p>
    <p>URL Film: <a href="{{ url_video_film }}">{{ url_video_film }}</a></p>

    <h3>Genre:</h3>
    {% if haveGenres %}
        <ul>
        {% for g in genre %}
            <li>{{ g.0 }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ genre }}</p>
    {% endif %}

    <h3>Asal Negara: {{ asal_negara }}</h3>

    <h3>Pemain:</h3>
    {% if haveActors %}
        <ul>
        {% for a in actors %}
            <li>{{ a.0 }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ actors }}</p>
    {% endif %}

    <h3>Penulis Skenario:</h3>
    {% if haveWriters %}
        <ul>
        {% for w in writers %}
            <li>{{ w.0 }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ writers }}</p>
    {% endif %}

    <h3>Sutradara: {{ sutradara }}</h3>

    <h3>Bagian Ulasan</h3>

    <form action="{% url 'main:insert_ulasan' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id_tayangan_post" value="{{ id }}">
        <textarea name="review_text" placeholder="Input untuk deskripsi ulasan"></textarea>
        <input type="number" name="rating" min="1" max="5" placeholder="rating yang diberikan" required>
        <button type="submit">Submit</button>
    </form>
    
    <h4>Daftar Ulasan:</h4>
    <ul>
        {% if haveUlasan %}
            {% for review in ulasan %}
            <li>
                <p>Username: {{ review.1 }}</p>
                <p>Diulas pada: {{ review.2 }}</p>
                <p>Deskripsi: {{ review.4 }}</p>
                <p>Rating: {{ review.3 }}</p>
            </li>
            {% endfor %}
        {% else %}
            <p>{{ ulasan }}</p>
        {% endif %}
    </ul>

    <div class="modal fade" id="unduhModal" tabindex="-1" role="dialog" aria-labelledby="unduhModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="unduhModalLabel">SUKSES MENAMBAHKAN TAYANGAN KE DAFTAR UNDUHAN
                        </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Selamat! Anda telah berhasil mengunduh [Judul Tayangan] dan akan
                    berlaku hingga [current time + 7 hari]. Cek informasi selengkapnya
                    pada halaman daftar unduhan.
                </div>
                <div class="modal-footer">
                    <a class="btn btn-primary">Daftar Unduhan</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="favoritModal" tabindex="-1" role="dialog" aria-labelledby="favoritModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="favoritModalLabel">TAMBAH KE DAFTAR FAVORIT MODAL</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="POST" action="{% url 'main:add_to_favorit' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <span>Judul Daftar Favorit:</span>
                        <input type="hidden" name="id_tayangan_favorit" value="{{ id }}">
                        <input type="hidden" name="judul_tayangan" value="{{ judul }}">
                        <select id="favoriteDropdown" name="daftar_favorit">
                            <option value="">Pilih Daftar Favorit</option>
                            {% for favorit in daftar_favorit %}
                                <option value="{{ favorit.0 }}">{{ favorit.0 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="submit">Tambah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</body>
{% if messages %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var myModal = new bootstrap.Modal(document.getElementById('downloadSuccessModal'));
    myModal.show();
  });
</script>
{% endif %}

<div class="modal fade" id="downloadSuccessModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">SUKSES MENAMBAHKAN TAYANGAN KE DAFTAR UNDUHAN</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a type="button" class="btn btn-primary" href="{% url 'main:daftar_unduhan' %}">Daftar Unduhan</a>
            </div>
        </div>
    </div>
</div>

<!-- TODO IMPLEMENT -->
<script>
    let isWatching = false;
    let startSliderPosition = 0;
    let startTime = null;

    document.getElementById('toggleButton').addEventListener('click', function() {
        const slider = document.getElementById('movieSlider');
        const id_tayangan = document.querySelector('input[name="id_tayangan_post"]').value;  // Get id_tayangan
        if (!isWatching) {
            // Start watching
            this.innerText = 'Stop';
            startSliderPosition = slider.value;
            startTime = new Date().toISOString().slice(0, 19).replace('T', ' ');  // Capture start time
        } else {
            // Stop watching
            this.innerText = 'Tonton';
            const endSliderPosition = slider.value;

            // Call Django view with AJAX
            const xhr = new XMLHttpRequest();
            xhr.open('POST', '/compute_riwayat_nonton/', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');  // Django CSRF token
            xhr.send(`start=${startSliderPosition}&end=${endSliderPosition}&startTime=${startTime}&id_tayangan=${id_tayangan}`);

            startTime = null;  // Reset start time
        }
        isWatching = !isWatching;
    });
</script>

{% endblock content %}

main/templates/halaman_series.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Halaman Tayangan</title>
{% endblock meta %}

{% block content %}

<body>
    <h1>HALAMAN SERIES</h1>
    <h2>Judul: {{ judul }}</h2>
    <h4>Episode:</h2>
    {% if haveEpisodes %}
        <ul>
        {% for e in episodes %}
        <!-- TODO GIVE LINKS -->
            <li><a href="{% url 'main:show_episode' id_tayangan=e.0 judul=judul sub_judul=e.1 %}">{{ e.1 }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ episodes }}</p>
    {% endif %}

    <form method="POST" action="{% url 'main:tambah_unduhan' %}">
        {% csrf_token %}
        <input type="hidden" name="id_tayangan_unduhan" value="{{ id }}">
        <input type="hidden" name="judul" value="{{ judul }}">
        <button type="submit" >Unduh Tayangan</button>
    </form>

    <button data-bs-toggle="modal" data-bs-target="#favoritModal">Favorit Tayangan</button>

    <p>Total View: {{ total_view }}</p>
    <p>Rating Rata-Rata: {{ avg_rating }}</p>
    <p>Sinopsis: {{ sinopsis }}</p>

    <h3>Genre:</h3>
    {% if haveGenres %}
        <ul>
        {% for g in genre %}
            <li>{{ g.0 }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ genre }}</p>
    {% endif %}

    <h3>Asal Negara: {{ asal_negara }}</h3>

    <h3>Pemain:</h3>
    {% if haveActors %}
        <ul>
        {% for a in actors %}
            <li>{{ a.0 }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ actors }}</p>
    {% endif %}

    <h3>Penulis Skenario:</h3>
    {% if haveWriters %}
        <ul>
        {% for w in writers %}
            <li>{{ w.0 }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{{ writers }}</p>
    {% endif %}

    <h3>Sutradara: {{ sutradara }}</h3>

    <h3>Bagian Ulasan</h3>

    <form action="{% url 'main:insert_ulasan' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id_tayangan_post" value="{{ id }}">
        <textarea name="review_text" placeholder="Input untuk deskripsi ulasan"></textarea>
        <input type="number" name="rating" min="1" max="5" placeholder="rating yang diberikan" required>
        <button type="submit">Submit</button>
    </form>
    
    <h4>Daftar Ulasan:</h4>
    <ul>
        {% if haveUlasan %}
            {% for review in ulasan %}
            <li>
                <p>Username: {{ review.1 }}</p>
                <p>Diulas pada: {{ review.2 }}</p>
                <p>Deskripsi: {{ review.4 }}</p>
                <p>Rating: {{ review.3 }}</p>
            </li>
            {% endfor %}
        {% else %}
            <p>{{ ulasan }}</p>
        {% endif %}
    </ul>

    <div class="modal fade" id="unduhModal" tabindex="-1" role="dialog" aria-labelledby="unduhModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="unduhModalLabel">SUKSES MENAMBAHKAN TAYANGAN KE DAFTAR UNDUHAN
                        </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Selamat! Anda telah berhasil mengunduh [Judul Tayangan] dan akan
                    berlaku hingga [current time + 7 hari]. Cek informasi selengkapnya
                    pada halaman daftar unduhan.
                </div>
                <div class="modal-footer">
                    <a class="btn btn-primary">Daftar Unduhan</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="favoritModal" tabindex="-1" role="dialog" aria-labelledby="favoritModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="favoritModalLabel">TAMBAH KE DAFTAR FAVORIT MODAL</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="POST" action="{% url 'main:add_to_favorit' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <span>Judul Daftar Favorit:</span>
                        <input type="hidden" name="id_tayangan_favorit" value="{{ id }}">
                        <input type="hidden" name="judul_tayangan" value="{{ judul }}">
                        <select id="favoriteDropdown" name="daftar_favorit">
                            <option value="">Pilih Daftar Favorit</option>
                            {% for favorit in daftar_favorit %}
                                <option value="{{ favorit.0 }}">{{ favorit.0 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="submit">Tambah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</body>

{% if messages %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var myModal = new bootstrap.Modal(document.getElementById('downloadSuccessModal'));
    myModal.show();
  });
</script>
{% endif %}

<div class="modal fade" id="downloadSuccessModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">SUKSES MENAMBAHKAN TAYANGAN KE DAFTAR UNDUHAN</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a type="button" class="btn btn-primary" href="{% url 'main:daftar_unduhan' %}">Daftar Unduhan</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div style="margin: auto; width: 20vw; padding-top: 30vh;"> 

    <h1>PacilFlix - C14</h1>
    <h2>Welcome {{ request.session.username }}</h2>
    {% if request.session.logged_in %}
    {% else %}
        <table>

            <tr>    
                <td>
                <button><a style="text-decoration: none;" href="{% url 'authentication:login' %}">Login</a>
                </button>
                </td>
            </tr>   

            <tr>
                <td>
                    <button><a style="text-decoration: none;" href="{% url 'authentication:register_pengguna' %}">Register</a>
                    </button>
                </td>
            </tr>


        </table>

     
     {% endif %}

{% endblock content %}